#Tools for EDA - Study of Numpy Library
#Experimnt No. 8
###Bidisha Chaudhuri PRN: 25070123034
###EnTC A-2

Numpy - Faster than lists, used for numerical computation, base for pandas

In [5]:
#Declaration of NumPy
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.array([[1,2,3], [4,5,6]])
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [6]:
#Dimension of Array
print(a.ndim)
print(b.ndim)



1
2


In [7]:
#Shape (How many members are there)
print(a.shape)
print(b.shape)

(4,)
(2, 3)


In [8]:
#Datatype (Integer form)

print(a.dtype)
print(b.dtype)

int64
int64


In [15]:
#Matrix Multiplication

print(np.zeros((2,3)))   #2,3 shows the size, 2 rows and 3 columns



[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
print(np.zeros((3,3)))    # 3 rows and 3 columns

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
print(np.eye((3)))   #Diagonal Matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [24]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [26]:
c = a*2
d = a+5
print(c)
print(d)

[20 40 60 80]
[15 25 35 45]


In [27]:
a+5  #Check the first code

array([15, 25, 35, 45])

In [28]:
#Average
print(np.mean(a))

25.0


In [29]:
np.mean(a)

np.float64(25.0)

In [30]:
np.median(a)

np.float64(25.0)

In [31]:
np.max(a)

np.int64(40)